---
- name: Provision All hosts.
  hosts: all
  become: true

  vars:
    docker_users:
      - ubuntu

  pre_tasks:
    - name: Update apt cache and upgrade packages.
      apt:
        upgrade: 'yes'
        update_cache: true
        cache_valid_time: 3600

  roles:
    - geerlingguy.docker

- name: Setup Security Host.
  import_playbook: security.yml

- name: Setup Attack Host.
  import_playbook: attack.yml

- name: Setup Target Host.
  import_playbook: target.yml
